// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $sign_up from "./routes/sign_up.tsx";
import * as $LoginPage from "./islands/LoginPage.tsx";
import * as $SignUpPage from "./islands/SignUpPage.tsx";
import * as $TopNavUser from "./islands/TopNavUser.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/sign_up.tsx": $sign_up,
  },
  islands: {
    "./islands/LoginPage.tsx": $LoginPage,
    "./islands/SignUpPage.tsx": $SignUpPage,
    "./islands/TopNavUser.tsx": $TopNavUser,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
